name: Automatyczny Monitor Cennika

on:
  schedule:
    # Uruchamia skrypt 4 razy na dobę (godziny: 00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Pozwala odpalić skrypt w dowolnym momencie ręcznie z GitHuba

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Pobranie kodu
      uses: actions/checkout@v3

    - name: Konfiguracja Pythona
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalacja zależności
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps chromium

    - name: Uruchomienie bota
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python monitor.py
